TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS BELOW HERE

# Install databases, templates & substitutions like this
DB += Watlow_PM_Alarm.db
DB += Watlow_PM_Analog_Input.db
DB += Watlow_PM_General.db
DB += Watlow_PM_IOC_Alarm.db
DB += Watlow_PM_Limits.db
DB += Watlow_PM_Linearization.db
DB += Watlow_PM_Loop_PID.db
DB += Watlow_PM_Loop.db
DB += Watlow_PM_Monitor.db
DB += Watlow_PM_Output_1.db
DB += Watlow_PM_Output_2_and_3.db
DB += Watlow_PM_Process_Value.db


# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_TEMPLATE = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD EXTRA GNUMAKE RULES BELOW HERE

